"use client";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/component/Navbar";
import BgVideo from "@/component/reuseable/BgVideo";
import Footer from "@/component/Footer";
import { usePathname } from "next/navigation";
import Aos from "aos";
import "aos/dist/aos.css";
import { useEffect } from "react";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const pathname = usePathname();
  const excludedRoutes = ["/termsandconditions", "/privacypolicy"];
  useEffect(() => {
    Aos.init({
      offset: 200,
      duration: 600,
      easing: 'ease-in-sine',
      delay: 100,
    });
  }, []);
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" />
        <title>THE CODING COMPANY</title>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable}`}
      >
        {!excludedRoutes.includes(pathname) ? (
          <div  className=" overflow-x-hidden">
            <Navbar />
            <BgVideo />
            <div id="main" className=" relative z-10">
              {children}
            </div>
            <Footer />
          </div>
        ) : (
          <>{children}</>
        )}
      </body>
    </html>
  );
}
